# Generated by Django 5.1.1 on 2025-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=False),
            preserve_default=False,
        ),
    ]
