# Generated by Django 5.1.1 on 2025-01-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_client_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
    ]
